### ISSUE TITLE
Ventura Support

### ISSUE THREAD

**Issue by Joseph-Hui** [kefrulz/ThinkpadRyzen-3500U-igpu-Hackintosh#1]
Can Ventura be installed?

**Comment by kefrulz** [comment]
I have updated OpenCore and instructions. It should support Ventura now

**Comment by lxstz1** [comment]
> I have updated OpenCore and instructions. It should support Ventura now

ventura does not support i already tried the upgrade from monterey and it will not boot after random code it will restart the laptop, Now I'm looking for a way to install Ventura...
