### ISSUE TITLE
Instal via Windows 

### ISSUE THREAD

**Issue by lxstz1** [kefrulz/ThinkpadRyzen-3500U-igpu-Hackintosh#2]
Is there a way to install via windows? because I don't have Mac OS.

**Comment by lxstz1** [comment]
I have managed to enter the EFI folder but after changing and booting install Monterey it always sticks in the section successfully spawned syslogd[57] because speculative. Is there a way to fix it?

**Comment by kefrulz** [comment]
I think you can use GibMacOS https://github.com/corpnewt/gibMacOS to create a recovery USB. This means that you will have to connect via Ethernet since this is an Internet MACOS isntall

**Comment by lxstz1** [comment]
> I think you can use GibMacOS https://github.com/corpnewt/gibMacOS to create a recovery USB. This means that you will have to connect via Ethernet since this is an Internet MACOS isntall



> I think you can use GibMacOS https://github.com/corpnewt/gibMacOS to create a recovery USB. This means that you will have to connect via Ethernet since this is an Internet MACOS isntall

Thanks for the suggestion, but I have installed it via Mac, new problems arise every time you want to boot always stuck in "lilu patcher failed to solve dce_panel_cntl"
And I also don't understand this step "Paste the EFI from this repo inside a EFI Folder (Structure should be EFI>EFI>(OC and OC folders)"

**Comment by kefrulz** [comment]
Add ne on Discord. My id is : ovidiu_13111 . We can connect there and i can help you fix it

**Comment by lxstz1** [comment]
> Add ne on Discord. My id is : ovidiu_13111 . We can connect there and i can help you fix it

No, I'm so happy that it's finally working after trying to use the OC as per what's in the repo!!,😆😆

**Comment by kefrulz** [comment]
I have updated it. I will add now the latest NootedRed.Kext version. Pllease make sure you download it again in a few minutes. Also, pelase use OCAT instead of ProperTree. It is a great tool and makes the process much easier.

**Comment by kefrulz** [comment]
> > Add ne on Discord. My id is : ovidiu_13111 . We can connect there and i can help you fix it
> 
> No, I'm so happy that it's finally working after trying to use the OC as per what's in the repo!!,😆😆

I am happy it works for you! It was my first Ryzen iGPU hackintosh. I no longer have the laptop to test new configs, but at the time it worked great.

**Comment by kefrulz** [comment]
Issue closed since install was successful.
